DROP TABLE AUTH_GROUP CASCADE CONSTRAINTS;
DROP TABLE AUTH_GROUP_PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE  AUTH_PERMISSION CASCADE CONSTRAINTS;
DROP TABLE AUTH_USER CASCADE CONSTRAINTS;
DROP TABLE AUTH_USER_GROUPS CASCADE CONSTRAINTS;
DROP TABLE AUTH_USER_USER_PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE DJANGO_CONTENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE DJANGO_MIGRATIONS CASCADE CONSTRAINTS;
DROP TABLE DJANGO_ADMIN_LOG CASCADE CONSTRAINTS;
DROP TABLE DJANGO_SESSION CASCADE CONSTRAINTS;
DROP TABLE misite_miusuario CASCADE CONSTRAINTS;
DROP TABLE misite_carrito CASCADE CONSTRAINTS;
DROP TABLE misite_carrito_items CASCADE CONSTRAINTS;
DROP TABLE misite_categoria CASCADE CONSTRAINTS;
DROP TABLE misite_itemcarrito CASCADE CONSTRAINTS;
DROP TABLE misite_miusuario_groups CASCADE CONSTRAINTS;
DROP TABLE misite_producto CASCADE CONSTRAINTS;



INSERT INTO MISITE_CATEGORIA VALUES(1, 'Acci�n');
INSERT INTO MISITE_CATEGORIA VALUES(2, 'Deporte');
INSERT INTO MISITE_CATEGORIA VALUES(3, 'Disparo');
INSERT INTO MISITE_CATEGORIA VALUES(4, 'rpg');
INSERT INTO MISITE_CATEGORIA VALUES(5, 'Terror');




INSERT INTO MISITE_PRODUCTO VALUES(1, 'Life is Strange', 19990, 1);
INSERT INTO MISITE_PRODUCTO VALUES(2, 'Detroit "Become human" ', 24550, 1);
INSERT INTO MISITE_PRODUCTO VALUES(3, 'Tony Howks pro Skater', 20000, 2);
INSERT INTO MISITE_PRODUCTO VALUES(4, 'FC24', 20990, 2);
INSERT INTO MISITE_PRODUCTO VALUES(5, 'Battlefield 2042', 8990, 3);
INSERT INTO MISITE_PRODUCTO VALUES(6, 'Fall out', 30990, 3);
INSERT INTO MISITE_PRODUCTO VALUES(7, 'The Witcher wild hunt 3', 15990, 4);
INSERT INTO MISITE_PRODUCTO VALUES(8, 'Elden Ring', 29990, 4);
INSERT INTO MISITE_PRODUCTO VALUES(9, 'The outlast Trials', 17990, 5);
INSERT INTO MISITE_PRODUCTO VALUES(10, 'Residen Evil 4 remake', 20990, 5);

select * from misite_miusuario;

select * from misite_producto;

SELECT * FROM misite_categoria;

select * from misite_carrito;